### ISSUE TITLE
The package cannot be found in CRAN

### ISSUE THREAD

**Issue by GaryBAYLOR** [blind-contours/CVtreeMLE#3]
The package cannot be accessed via link https://CRAN.R-project.org/package=CVtreeMLE or https://cran.r-project.org/web/packages/CVtreeMLE/index.html, and installation by running `install.packages("CVtreeMLE")`, as instructed in README file, will fail.

Please check if the package has been successfully submitted to CRAN.

**Comment by blind-contours** [comment]
Hi @GaryBAYLOR, thank you -- yes the CVtreeMLE package is currently not available on CRAN. This is because it depends currently on the sl3 ensemble machine learning package which is not on CRAN. The readme documentation has been updated. Future work will be done to get CVtreeMLE on CRAN, one approach for this is to instead build nonparametric estimators using the HAL9001 package (on CRAN) which is a nonparametric estimator with asymptoticly efficient properties.  In the meantime, CVtreeMLE must be downloaded from this repository.

**Comment by GaryBAYLOR** [comment]
If you intent to submit the package to CRAN after publishing the paper, can you also update the Availability Section in the paper to remove the statement that the package has been publicly available on CRAN, since it is not so far and it may take a certain amount of time to do that after publishing the paper. Instead, you can update the README file in the Github repo later to let the audience know it is on CRAN.

**Comment by blind-contours** [comment]
I have edited the availability section to reflect that the package is currently not on CRAN.
