### ISSUE TITLE
Comments on README file

### ISSUE THREAD

**Issue by GaryBAYLOR** [blind-contours/CVtreeMLE#8]
* Simulation plots
In the plot that explains the simulation settings, please explain what does the plot on the left (with orange cube) represent (co-variables? then why three dimensions?), what is the relationship between A, W and M1, M2, M3? What is the difference between M1, M2,M3 in the left plot with those in the right plot?

* number of folds in cross-validation
It makes sense to use a higher value of `n_folds` instead of 2 to see how the results look like, as typically in cross-validation, higher number of folds(e.g., `n_folds` = 4, 8, 10, etc.) are used.

**Comment by ghost** [comment]
I'll also post related comments under this issue, to keep things organized.

**Comment by ghost** [comment]
contributions: the contribution link `https://github.com/blind-contours/CVtreeMLE/blob/master/CONTRIBUTING.md` does not lead anywhere

**Comment by ghost** [comment]
I'll add here the following:

  - there's substantial example usage for simulation, both here and in the vignette, but a real world example would be really helpful
  - since there's such integration with SL3, a brief discussion of intended use (in text, not code) would probably be warranted, especially because it seems like some of the package's behavioral guarantees really rely on that package

**Comment by blind-contours** [comment]
I have updated the brief explanation of the simulation and the respective "mixture cube". I've increased the nfolds to 5, originally it was smaller for easier testing of the package. I've added a real world example in the vignette and there is a breast cancer example in the tests. I've included discussion of ML via SL3 in the readme and vignette.
